#!/usr/bin/env bash

update_git_repo() {
	cd $1
	if [ -d .git ]; then
		mv .git .git.custom
	fi
	mv .git.orig .git
	git pull
	mv .git .git.orig
	if [ -d .git.custom ]; then
		mv .git.custom .git
	fi
	cd - >/dev/null
}

echo_line_break() {
	echo "------------------------------------------------------------"
}

echo "Updating mediawiki core"
update_git_repo `dirname $0`

echo_line_break
echo "Updating extensions"
for ext_git_dir in extensions/*/.git.orig; do
	ext_base_dir=`dirname $ext_git_dir`
	echo_line_break
	echo "Update $ext_base_dir"
	update_git_repo $ext_base_dir
done

echo_line_break
echo "Done"
